#include "config/config_store.h"

#include <algorithm>
#include <fstream>
#include <sstream>
#include <cctype>

namespace changeos {
namespace config {

namespace {

std::string trim(const std::string& s) {
    size_t start = 0;
    while (start < s.size() && std::isspace(static_cast<unsigned char>(s[start]))) ++start;
    size_t end = s.size();
    while (end > start && std::isspace(static_cast<unsigned char>(s[end - 1]))) --end;
    return s.substr(start, end - start);
}

std::string escape(const std::string& value) {
    std::string out;
    out.reserve(value.size() + 2);
    for (char c : value) {
        switch (c) {
            case '\n': out += "\\n"; break;
            case '\r': out += "\\r"; break;
            case '\t': out += "\\t"; break;
            case '\\': out += "\\\\"; break;
            default: out += c;
        }
    }
    return out;
}

std::string unescape(const std::string& value) {
    std::string out;
    out.reserve(value.size());
    for (size_t i = 0; i < value.size(); ++i) {
        if (value[i] == '\\' && i + 1 < value.size()) {
            char next = value[++i];
            switch (next) {
                case 'n': out += '\n'; break;
                case 'r': out += '\r'; break;
                case 't': out += '\t'; break;
                case '\\': out += '\\'; break;
                default: out += next;
            }
        } else {
            out += value[i];
        }
    }
    return out;
}

std::vector<std::string> split_list(const std::string& value) {
    std::vector<std::string> result;
    std::string token;
    for (size_t i = 0; i < value.size(); ++i) {
        char c = value[i];
        if (c == ',') {
            result.push_back(trim(token));
            token.clear();
        } else {
            token += c;
        }
    }
    if (!token.empty()) result.push_back(trim(token));
    return result;
}

} // namespace

ConfigStore::ConfigStore() {
    values_["filesystem.enabled"] = "true";
    values_["filesystem.poll_interval_ms"] = "2000";
    values_["filesystem.use_native"] = "true";
    values_["filesystem.watch_paths"] = "/etc,/tmp";

    values_["process.enabled"] = "true";
    values_["process.poll_interval_ms"] = "3000";
    values_["process.track_cpu"] = "true";
    values_["process.track_memory"] = "true";

    values_["network.enabled"] = "true";
    values_["network.poll_interval_ms"] = "5000";

    values_["system_config.enabled"] = "true";
    values_["system_config.poll_interval_ms"] = "10000";

    values_["storage.database_path"] = "change-of-system.db";
    values_["storage.max_events"] = "100000";

    values_["reporting.enabled"] = "false";
    values_["reporting.endpoint"] = "https://example.com/api/events";
    values_["reporting.api_key"] = "";
    values_["reporting.batch_size"] = "100";
    values_["reporting.interval_ms"] = "10000";
}

void ConfigStore::load(const std::string& path) {
    std::lock_guard<std::mutex> lock(mutex_);
    file_path_ = path;
    std::ifstream file(path);
    if (!file) return;

    std::string line;
    while (std::getline(file, line)) {
        std::string trimmed = trim(line);
        if (trimmed.empty() || trimmed[0] == '#' || trimmed[0] == ';') continue;
        auto eq = trimmed.find('=');
        if (eq == std::string::npos) continue;
        std::string key = trim(trimmed.substr(0, eq));
        std::string value = unescape(trim(trimmed.substr(eq + 1)));
        if (!key.empty()) values_[key] = value;
    }
}

void ConfigStore::save(const std::string& path) const {
    std::lock_guard<std::mutex> lock(mutex_);
    std::ofstream file(path.empty() ? file_path_ : path);
    if (!file) return;
    file << "# change-of-system configuration\n";
    file << "# Auto-generated by ConfigStore\n\n";
    for (const auto& [key, value] : values_) {
        file << key << " = " << escape(value) << "\n";
    }
}

std::string ConfigStore::get(const std::string& key,
                             const std::string& default_value) const {
    std::lock_guard<std::mutex> lock(mutex_);
    auto it = values_.find(key);
    return it == values_.end() ? default_value : it->second;
}

int ConfigStore::get_int(const std::string& key, int default_value) const {
    std::string v = get(key);
    if (v.empty()) return default_value;
    try {
        return std::stoi(v);
    } catch (...) {
        return default_value;
    }
}

bool ConfigStore::get_bool(const std::string& key, bool default_value) const {
    std::string v = get(key);
    if (v.empty()) return default_value;
    std::transform(v.begin(), v.end(), v.begin(),
                   [](unsigned char c) { return std::tolower(c); });
    if (v == "true" || v == "1" || v == "yes" || v == "on") return true;
    if (v == "false" || v == "0" || v == "no" || v == "off") return false;
    return default_value;
}

std::vector<std::string> ConfigStore::get_list(
    const std::string& key,
    const std::vector<std::string>& default_value) const {
    std::string v = get(key);
    if (v.empty()) return default_value;
    return split_list(v);
}

void ConfigStore::set(const std::string& key, const std::string& value) {
    std::lock_guard<std::mutex> lock(mutex_);
    values_[key] = value;
}

void ConfigStore::set_int(const std::string& key, int value) {
    set(key, std::to_string(value));
}

void ConfigStore::set_bool(const std::string& key, bool value) {
    set(key, value ? "true" : "false");
}

void ConfigStore::set_list(const std::string& key,
                           const std::vector<std::string>& value) {
    std::ostringstream oss;
    for (size_t i = 0; i < value.size(); ++i) {
        if (i > 0) oss << ", ";
        oss << value[i];
    }
    set(key, oss.str());
}

bool ConfigStore::has(const std::string& key) const {
    std::lock_guard<std::mutex> lock(mutex_);
    return values_.find(key) != values_.end();
}

} // namespace config
} // namespace changeos
