set(COS_PLATFORM "Unknown")

if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(COS_PLATFORM "Linux")
    add_definitions(-DCOS_PLATFORM_LINUX=1)
    if(ANDROID)
        set(COS_PLATFORM "Android")
        add_definitions(-DCOS_PLATFORM_ANDROID=1)
    endif()
elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    set(COS_PLATFORM "macOS")
    add_definitions(-DCOS_PLATFORM_MACOS=1)
    if(IOS)
        set(COS_PLATFORM "iOS")
        add_definitions(-DCOS_PLATFORM_IOS=1)
    endif()
elseif(CMAKE_SYSTEM_NAME STREQUAL "Windows")
    set(COS_PLATFORM "Windows")
    add_definitions(-DCOS_PLATFORM_WINDOWS=1)
elseif(CMAKE_SYSTEM_NAME STREQUAL "ChromeOS")
    set(COS_PLATFORM "ChromeOS")
    add_definitions(-DCOS_PLATFORM_CHROMEOS=1)
elseif(CMAKE_SYSTEM_NAME STREQUAL "FydeOS")
    set(COS_PLATFORM "FydeOS")
    add_definitions(-DCOS_PLATFORM_FYDEOS=1)
elseif(UNIX)
    set(COS_PLATFORM "UnixLike")
    add_definitions(-DCOS_PLATFORM_UNIX=1)
endif()

set(COS_PLATFORM "${COS_PLATFORM}" CACHE STRING "Target platform" FORCE)
